name: base
channels:
  - defaults
  - pyg
dependencies:
- pip=21.2.4
- conda-forge::cudatoolkit=11.3.1
- python=3.8
- conda-forge::dash=2.5.1
- conda-forge::dash-bootstrap-components=1.1.0
- conda-forge::werkzeug=2.1.2
- conda-forge::dash_cytoscape=0.2.0
- conda-forge::dash_daq=0.5.0
- pytorch::torchvision
- pytorch::torchaudio
- pyg=2.0.4
- gunicorn=20.1.0